apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - resources:
        limits:
          cpu: 0.5
      image: mysql:5.6
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql.env
              key: mysql.root.password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql.env
              key: mysql.database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql.env
              key: mysql.username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql.env
              key: mysql.password
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
          # This name must match the volumes.name below.
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      gcePersistentDisk:
        # This disk must already exist.
        pdName: cms-mysql
        fsType: ext4
