apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-disk-redis
  labels:
      name: redis-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: cms-redis
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-disk-mysql
  labels:
      name: mysql-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: cms-mysql
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-disk-mongo
  labels:
      name: mongo-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: cms-mongo
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-disk-media
  labels:
      name: media-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: cms-media
    fsType: ext4